Set-StrictMode -Version Latest

function Get-MeetingPackRevision([string]$Path) {
  $sha=[Security.Cryptography.SHA256]::Create(); $stream=[IO.File]::OpenRead($Path)
  try { ([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-','').ToLowerInvariant() } finally { $stream.Dispose(); $sha.Dispose() }
}

function Test-MeetingPackPin([string]$Pin,[string]$ConfigPath) {
  if([string]::IsNullOrWhiteSpace($Pin) -or -not(Test-Path -LiteralPath $ConfigPath -PathType Leaf)){return $false}
  $c=Get-Content -LiteralPath $ConfigPath -Raw|ConvertFrom-Json
  $salt=[Convert]::FromBase64String([string]$c.salt);$expected=[Convert]::FromBase64String([string]$c.hash)
  $k=[Security.Cryptography.Rfc2898DeriveBytes]::new($Pin,$salt,[int]$c.iterations)
  try{$actual=$k.GetBytes($expected.Length)}finally{$k.Dispose()};$diff=0
  for($i=0;$i-lt$expected.Length;$i++){$diff=$diff-bor($expected[$i]-bxor$actual[$i])};$diff-eq 0
}

function Get-MeetingPackLead($p) {
  foreach($n in @('projectLead','leadName','owner')){if($p.PSObject.Properties.Name-contains$n-and-not[string]::IsNullOrWhiteSpace([string]$p.$n)){return([string]$p.$n).Trim()}}
  if($p.people){return(@($p.people)-join', ')};'Unassigned'
}

function Get-MeetingPackStatus([string]$s) {
  switch -Regex ($s.Trim().ToLowerInvariant()){'^(todo|to do|backlog)$'{'To Do';break};'^(doing|in progress|active)$'{'In Progress';break};'^(blocked|on hold)$'{'Blocked';break};'^(done|complete|completed)$'{'Done';break};default{if($s){$s}else{'To Do'}}}
}

function Get-MeetingPackProjects([string]$Path,[string[]]$Ids) {
  $root=Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json
  $all=if($root-is[Array]){@($root)}elseif($root.PSObject.Properties.Name-contains'projects'){@($root.projects)}elseif($root.PSObject.Properties.Name-contains'cards'){@($root.cards)}else{throw 'Invalid projects data.'}
  $map=@{};foreach($p in $all){$map[[string]$p.id]=$p};$chosen=if($Ids.Count){foreach($id in $Ids){if(-not$map.ContainsKey($id)){throw "Project was not found: $id"};$map[$id]}}else{$all}
  @($chosen|ForEach-Object{[pscustomobject]@{id=[string]$_.id;name=[string]$_.title;nextAction=$(if(-not[string]::IsNullOrWhiteSpace([string]$_.nextAction)){[string]$_.nextAction}elseif(-not[string]::IsNullOrWhiteSpace([string]$_.next)){[string]$_.next}else{'No next action recorded'});status=Get-MeetingPackStatus([string]$_.status);lead=Get-MeetingPackLead $_;update=$(if(-not[string]::IsNullOrWhiteSpace([string]$_.context)){[string]$_.context}else{'No update recorded'})}})
}

function ConvertTo-MeetingPackMarkdown($m,$projects) {
  $l=@('---','title: SAMI Meeting Pack',"classification: $($m.classification)","generated_at_adelaide: '$($m.time)'","scope: '$(([string]$m.scope).Replace("'","''"))'","revision: $($m.revision)",'brand: SAMI','brand_mark: circular_sami_mark','prepared_from: SAMI Kanban',"project_count: $($projects.Count)",'---','',"# SAMI Meeting Pack - $($m.classification)",'')
  if($m.classification-eq'Preview'){$l+=@('> **PREVIEW - NOT AUTHORISED**','')}
  foreach($p in $projects){$l+=@("## $(([string]$p.name).Replace('#','\#'))",'',"**Next Action:** $($p.nextAction)",'',"- **Status:** $($p.status)","- **Project Lead:** $($p.lead)",'','### Latest Update','',[string]$p.update,'')}
  [Text.UTF8Encoding]::new($false).GetBytes(($l-join"`n")+"`n")
}

function Add-MeetingPackZipText($zip,[string]$name,[string]$text){$e=$zip.CreateEntry($name);$w=[IO.StreamWriter]::new($e.Open(),[Text.UTF8Encoding]::new($false));try{$w.Write($text)}finally{$w.Dispose()}}
function Add-MeetingPackZipBytes($zip,[string]$name,[byte[]]$bytes){$e=$zip.CreateEntry($name);$stream=$e.Open();try{$stream.Write($bytes,0,$bytes.Length)}finally{$stream.Dispose()}}
function ConvertTo-MeetingPackXml([object]$v){[Security.SecurityElement]::Escape([string]$v)}
function New-MeetingPackXlsx($m,$projects) {
  Add-Type -AssemblyName System.IO.Compression;$ms=[IO.MemoryStream]::new();$z=[IO.Compression.ZipArchive]::new($ms,[IO.Compression.ZipArchiveMode]::Create,$true)
  try{
    Add-MeetingPackZipText $z '[Content_Types].xml' '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/tables/table1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml"/><Override PartName="/docProps/custom.xml" ContentType="application/vnd.openxmlformats-officedocument.custom-properties+xml"/></Types>'
    Add-MeetingPackZipText $z '_rels/.rels' '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties" Target="docProps/custom.xml"/></Relationships>'
    Add-MeetingPackZipText $z 'xl/workbook.xml' '<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Summary" sheetId="1" r:id="rId1"/><sheet name="Projects" sheetId="2" r:id="rId2"/></sheets></workbook>'
    Add-MeetingPackZipText $z 'xl/_rels/workbook.xml.rels' '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'
    Add-MeetingPackZipText $z 'xl/styles.xml' '<?xml version="1.0"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="4"><font><sz val="11"/></font><font><b/><color rgb="FFFFFFFF"/></font><font><b/><color rgb="FF006B70"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="16"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF006B70"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFD9EFED"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="9"><xf fontId="0" fillId="0" borderId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf fontId="1" fillId="2" borderId="0" applyAlignment="1"><alignment wrapText="1"/></xf><xf fontId="2" fillId="0" borderId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf fontId="3" fillId="2" borderId="0"/><xf fontId="2" fillId="3" borderId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf fontId="2" fillId="3" borderId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf fontId="2" fillId="3" borderId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf fontId="2" fillId="3" borderId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf fontId="2" fillId="3" borderId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf></cellXfs></styleSheet>'
    function C([string]$r,[object]$v,[int]$s=0){'<c r="'+$r+'" t="inlineStr" s="'+$s+'"><is><t xml:space="preserve">'+(ConvertTo-MeetingPackXml $v)+'</t></is></c>'}
    $rows=@('<row r="1" ht="48" customHeight="1">'+(C B1 'SAMI Meeting Pack' 3)+'</row>');$pairs=@(@('Classification',$m.classification),@('Generated (Adelaide)',$m.time),@('Scope',$m.scope),@('Revision',$m.revision.Substring(0,12)),@('Prepared from','SAMI Kanban'),@('Exported projects',$projects.Count));$r=3;foreach($p in $pairs){$rows+='<row r="'+$r+'">'+(C ('A'+$r) $p[0] 2)+(C ('B'+$r) $p[1])+'</row>';$r++};if($m.classification-eq'Preview'){$rows+='<row r="10">'+(C A10 'PREVIEW - NOT AUTHORISED' 1)+'</row>'};Add-MeetingPackZipText $z 'xl/worksheets/sheet1.xml' ('<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><cols><col min="1" max="1" width="24" customWidth="1"/><col min="2" max="3" width="35" customWidth="1"/></cols><sheetData>'+($rows-join'')+'</sheetData><mergeCells count="1"><mergeCell ref="B1:C1"/></mergeCells><drawing r:id="rId1"/></worksheet>');Add-MeetingPackZipText $z 'xl/worksheets/_rels/sheet1.xml.rels' '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>';$logoPath=Join-Path $PSScriptRoot 'assets\icons\sami_project_portfolio-192.png';if(Test-Path -LiteralPath $logoPath){Add-MeetingPackZipBytes $z 'xl/media/sami-mark.png' ([IO.File]::ReadAllBytes($logoPath));Add-MeetingPackZipText $z 'xl/drawings/drawing1.xml' '<?xml version="1.0"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><xdr:oneCellAnchor><xdr:from><xdr:col>0</xdr:col><xdr:colOff>250000</xdr:colOff><xdr:row>0</xdr:row><xdr:rowOff>80000</xdr:rowOff></xdr:from><xdr:ext cx="520000" cy="520000"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="1" name="Circular SAMI mark"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="rId1"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="ellipse"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor></xdr:wsDr>';Add-MeetingPackZipText $z 'xl/drawings/_rels/drawing1.xml.rels' '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/sami-mark.png"/></Relationships>'}
    $rows=@('<row r="1" ht="28" customHeight="1">'+(C A1 'Use Ctrl+F to search or the column filters to narrow projects.' 4)+'</row>','<row r="2" ht="26" customHeight="1">'+(C A2 'Project Name' 1)+(C B2 'Next Action' 1)+(C C2 Status 1)+(C D2 'Project Lead' 1)+(C E2 'Latest Update' 1)+'</row>');$r=3;foreach($p in $projects){$statusStyle=switch($p.status){'To Do'{5};'In Progress'{6};'Blocked'{7};'Done'{8};default{0}};$rows+='<row r="'+$r+'" ht="44" customHeight="1">'+(C ('A'+$r) $p.name 2)+(C ('B'+$r) $p.nextAction 4)+(C ('C'+$r) $p.status $statusStyle)+(C ('D'+$r) $p.lead)+(C ('E'+$r) $p.update)+'</row>';$r++};$last=[Math]::Max(2,$r-1)
    Add-MeetingPackZipText $z 'xl/worksheets/sheet2.xml' ('<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetViews><sheetView workbookViewId="0"><pane xSplit="2" ySplit="2" topLeftCell="C3" activePane="bottomRight" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="32" customWidth="1"/><col min="2" max="2" width="52" customWidth="1"/><col min="3" max="3" width="18" customWidth="1"/><col min="4" max="4" width="24" customWidth="1"/><col min="5" max="5" width="58" customWidth="1"/></cols><sheetData>'+($rows-join'')+'</sheetData><mergeCells count="1"><mergeCell ref="A1:E1"/></mergeCells><autoFilter ref="A2:E'+$last+'"/><tableParts count="1"><tablePart r:id="rId1"/></tableParts></worksheet>');Add-MeetingPackZipText $z 'xl/worksheets/_rels/sheet2.xml.rels' '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" Target="../tables/table1.xml"/></Relationships>'
    Add-MeetingPackZipText $z 'xl/tables/table1.xml' ('<?xml version="1.0"?><table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" id="1" name="ProjectsTable" displayName="ProjectsTable" ref="A2:E'+$last+'" totalsRowShown="0"><autoFilter ref="A2:E'+$last+'"/><tableColumns count="5"><tableColumn id="1" name="Project Name"/><tableColumn id="2" name="Next Action"/><tableColumn id="3" name="Status"/><tableColumn id="4" name="Project Lead"/><tableColumn id="5" name="Latest Update"/></tableColumns><tableStyleInfo name="TableStyleMedium2" showRowStripes="1"/></table>');Add-MeetingPackZipText $z 'docProps/custom.xml' ('<?xml version="1.0"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="BoardRevision"><vt:lpwstr>'+$m.revision+'</vt:lpwstr></property></Properties>')
  }finally{$z.Dispose()};$ms.ToArray()
}

function New-MeetingPackPdf($m,$projects) {
  $blocks=foreach($p in $projects){'<section><h2>'+(ConvertTo-MeetingPackXml $p.name)+'</h2><div class="next"><b>Next Action</b><p>'+(ConvertTo-MeetingPackXml $p.nextAction)+'</p></div><b>Status:</b> '+(ConvertTo-MeetingPackXml $p.status)+'<br><b>Project Lead:</b> '+(ConvertTo-MeetingPackXml $p.lead)+'<h3>Latest Update</h3><p>'+(ConvertTo-MeetingPackXml $p.update)+'</p></section>'};$wm=if($m.classification-eq'Preview'){'<div class="wm">PREVIEW</div>'}else{''};$iconPath=Join-Path $PSScriptRoot 'assets\sami_project_portfolio.ico';$iconData=if(Test-Path -LiteralPath $iconPath){'data:image/x-icon;base64,'+[Convert]::ToBase64String([IO.File]::ReadAllBytes($iconPath))}else{''};$html='<!doctype html><meta charset="utf-8"><style>@page{size:A4;margin:16mm}body{font:11pt Arial;color:#173640}header{border-bottom:4px solid #007f82;padding:10px}.mark{width:52px;height:52px;vertical-align:middle;object-fit:contain}h1{display:inline;margin-left:15px;color:#006b70}section{break-inside:avoid;border-left:5px solid #007f82;padding:10px;margin:15px 0;background:#f3f9f8}.next{background:#d9efed;padding:8px;font-size:12pt}.wm{position:fixed;top:42%;left:12%;font-size:70pt;transform:rotate(-30deg);color:rgba(0,127,130,.13);z-index:-1}</style><header><img class="mark" src="'+$iconData+'" alt="SAMI"><h1>Meeting Pack</h1></header><p><b>'+$m.classification+'</b> · '+$m.time+' · '+(ConvertTo-MeetingPackXml $m.scope)+' · Revision '+$m.revision.Substring(0,12)+'<br>Prepared from: SAMI Kanban</p>'+$wm+($blocks-join'');$dir=Join-Path([IO.Path]::GetTempPath())('sami-mp-'+[guid]::NewGuid().ToString('n'));[IO.Directory]::CreateDirectory($dir)|Out-Null;$hp=Join-Path $dir pack.html;$pp=Join-Path $dir pack.pdf;[IO.File]::WriteAllText($hp,$html,[Text.UTF8Encoding]::new($false));$edge=@("${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe","$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")|Where-Object{Test-Path $_}|Select-Object -First 1;if(-not$edge){throw 'Installed Edge PDF engine is unavailable.'};$p=Start-Process $edge -ArgumentList @('--headless','--disable-gpu',"--print-to-pdf=$pp",('file:///'+$hp.Replace('\','/'))) -Wait -PassThru -WindowStyle Hidden;if($p.ExitCode-ne0-or-not(Test-Path $pp)){throw 'PDF generation failed.'};try{[IO.File]::ReadAllBytes($pp)}finally{Remove-Item $dir -Recurse -Force -ErrorAction SilentlyContinue}
}

function Invoke-MeetingPackExport([string]$Body,[string]$CanonicalPath,[string]$SnapshotPath,[string]$CanonicalRoot,[bool]$TeamReachable) {
  $q=$Body|ConvertFrom-Json;$f=([string]$q.format).ToLowerInvariant();$mode=([string]$q.mode).ToLowerInvariant();if($f-notin@('pdf','xlsx','md')){throw 'Invalid Meeting Pack format.'};if($mode-notin@('authorised','preview')){throw 'Invalid Meeting Pack mode.'}
  if($mode-eq'authorised'){if(-not$TeamReachable-or-not(Test-Path $CanonicalPath)){throw 'Canonical Team ESMI data is unavailable.'};$source=$CanonicalPath}else{$source=if(Test-Path $SnapshotPath){$SnapshotPath}else{$CanonicalPath}}
  $rev=Get-MeetingPackRevision $source;if(([string]$q.revision).ToLowerInvariant()-ne$rev){throw 'Board source changed. Refresh the board and try again.'};$projects=Get-MeetingPackProjects $source @($q.projectIds);$tz=[TimeZoneInfo]::FindSystemTimeZoneById('Cen. Australia Standard Time');$time=[TimeZoneInfo]::ConvertTimeFromUtc([datetime]::UtcNow,$tz).ToString('yyyy-MM-dd HH:mm:ss zzz');$m=[pscustomobject]@{classification=$(if($mode-eq'preview'){'Preview'}else{'Authorised'});time=$time;scope=[string]$q.scope;revision=$rev};$bytes=switch($f){md{ConvertTo-MeetingPackMarkdown $m $projects};xlsx{New-MeetingPackXlsx $m $projects};pdf{New-MeetingPackPdf $m $projects}}
  if($mode-eq'authorised'){$entry=[ordered]@{user=$env:USERNAME;timestampAdelaide=$time;format=$f;scope=$m.scope;revision=$rev;projectCount=$projects.Count;projectIds=@($projects.id)}|ConvertTo-Json -Compress;try{Add-Content -LiteralPath(Join-Path $CanonicalRoot 'data\meeting_pack_exports.jsonl') -Value $entry -Encoding UTF8 -ErrorAction Stop}catch{throw 'Meeting Pack audit persistence failed.'}}
  @{Bytes=$bytes;ContentType=$(switch($f){md{'text/markdown; charset=utf-8'};xlsx{'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};pdf{'application/pdf'}});FileName=('SAMI_Meeting_Pack_'+$m.classification+'_'+(Get-Date -Format yyyyMMdd_HHmmss)+'.'+$f)}
}

# Single-sheet workbook generator. Kept last so it supersedes the original implementation.
function New-MeetingPackXlsx($m,$projects) {
  Add-Type -AssemblyName System.IO.Compression
  $ms=[IO.MemoryStream]::new();$z=[IO.Compression.ZipArchive]::new($ms,[IO.Compression.ZipArchiveMode]::Create,$true)
  try {
    Add-MeetingPackZipText $z '[Content_Types].xml' '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/tables/table1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/><Override PartName="/docProps/custom.xml" ContentType="application/vnd.openxmlformats-officedocument.custom-properties+xml"/></Types>'
    Add-MeetingPackZipText $z '_rels/.rels' '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties" Target="docProps/custom.xml"/></Relationships>'
    Add-MeetingPackZipText $z 'xl/workbook.xml' '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView/></bookViews><sheets><sheet name="Projects" sheetId="1" r:id="rId1"/></sheets></workbook>'
    Add-MeetingPackZipText $z 'xl/_rels/workbook.xml.rels' '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'
    $styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="4"><font><sz val="11"/><name val="Aptos"/><family val="2"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FF006B70"/><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FF006B70"/><sz val="18"/><name val="Aptos Display"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF006B70"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFD9EFED"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"><color rgb="FFD6DEE8"/></left><right style="thin"><color rgb="FFD6DEE8"/></right><top style="thin"><color rgb="FFD6DEE8"/></top><bottom style="thin"><color rgb="FFD6DEE8"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="5"><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="3" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="3" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'
    Add-MeetingPackZipText $z 'xl/styles.xml' $styles
    function XCell([string]$r,[object]$v,[int]$style=0){'<c r="'+$r+'" t="inlineStr" s="'+$style+'"><is><t xml:space="preserve">'+(ConvertTo-MeetingPackXml $v)+'</t></is></c>'}
    $rows=New-Object Collections.Generic.List[string]
    $rows.Add('<row r="1" ht="52" customHeight="1">'+(XCell 'B1' 'SAMI Meeting Pack' 3)+'</row>')
    $subtitle=$m.classification+' | Generated '+$m.time+' | Revision '+$m.revision.Substring(0,12)+' | Prepared from: SAMI Kanban'
    $rows.Add('<row r="2" ht="28" customHeight="1">'+(XCell 'A2' $subtitle 4)+'</row>')
    $rows.Add('<row r="3" ht="26" customHeight="1">'+(XCell 'A3' 'Project Name' 1)+(XCell 'B3' 'Next Action' 1)+(XCell 'C3' 'Status' 1)+(XCell 'D3' 'Project Lead' 1)+(XCell 'E3' 'Latest Update' 1)+'</row>')
    $r=4;foreach($project in $projects){$rows.Add('<row r="'+$r+'" ht="48" customHeight="1">'+(XCell ('A'+$r) $project.name 2)+(XCell ('B'+$r) $project.nextAction 4)+(XCell ('C'+$r) $project.status)+(XCell ('D'+$r) $project.lead)+(XCell ('E'+$r) $project.update)+'</row>');$r++}
    $last=[Math]::Max(3,$r-1)
    $sheet='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetViews><sheetView workbookViewId="0"><pane xSplit="2" ySplit="3" topLeftCell="C4" activePane="bottomRight" state="frozen"/><selection pane="bottomRight" activeCell="C4" sqref="C4"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/><cols><col min="1" max="1" width="32" customWidth="1"/><col min="2" max="2" width="52" customWidth="1"/><col min="3" max="3" width="18" customWidth="1"/><col min="4" max="4" width="24" customWidth="1"/><col min="5" max="5" width="58" customWidth="1"/></cols><sheetData>'+($rows-join'')+'</sheetData><mergeCells count="2"><mergeCell ref="B1:E1"/><mergeCell ref="A2:E2"/></mergeCells><drawing r:id="rId1"/><tableParts count="1"><tablePart r:id="rId2"/></tableParts></worksheet>'
    Add-MeetingPackZipText $z 'xl/worksheets/sheet1.xml' $sheet
    Add-MeetingPackZipText $z 'xl/worksheets/_rels/sheet1.xml.rels' '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" Target="../tables/table1.xml"/></Relationships>'
    Add-MeetingPackZipText $z 'xl/tables/table1.xml' ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" id="1" name="ProjectsTable" displayName="ProjectsTable" ref="A3:E'+$last+'" totalsRowShown="0"><autoFilter ref="A3:E'+$last+'"/><tableColumns count="5"><tableColumn id="1" name="Project Name"/><tableColumn id="2" name="Next Action"/><tableColumn id="3" name="Status"/><tableColumn id="4" name="Project Lead"/><tableColumn id="5" name="Latest Update"/></tableColumns><tableStyleInfo name="TableStyleMedium2" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/></table>')
    $logo=Join-Path $PSScriptRoot 'assets\icons\sami_project_portfolio-192.png';if(-not(Test-Path -LiteralPath $logo)){throw 'SAMI workbook branding icon is unavailable.'};Add-MeetingPackZipBytes $z 'xl/media/sami-mark.png' ([IO.File]::ReadAllBytes($logo))
    Add-MeetingPackZipText $z 'xl/drawings/drawing1.xml' '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><xdr:oneCellAnchor><xdr:from><xdr:col>0</xdr:col><xdr:colOff>180000</xdr:colOff><xdr:row>0</xdr:row><xdr:rowOff>90000</xdr:rowOff></xdr:from><xdr:ext cx="500000" cy="500000"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="1" name="Circular SAMI mark"/><xdr:cNvPicPr preferRelativeResize="0"/></xdr:nvPicPr><xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="rId1"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="500000" cy="500000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor></xdr:wsDr>'
    Add-MeetingPackZipText $z 'xl/drawings/_rels/drawing1.xml.rels' '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/sami-mark.png"/></Relationships>'
    Add-MeetingPackZipText $z 'docProps/custom.xml' ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="BoardRevision"><vt:lpwstr>'+$m.revision+'</vt:lpwstr></property></Properties>')
  } finally {$z.Dispose()}
  return $ms.ToArray()
}