[CmdletBinding()]
param([switch]$KeepTemp)
$ErrorActionPreference = 'Stop'
$RepoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$TempRoot = Join-Path ([IO.Path]::GetTempPath()) ('SAMI-project-history-' + [Guid]::NewGuid().ToString('N'))
$CanonicalRoot = Join-Path $TempRoot 'canonical'
$RuntimeRoot = Join-Path $TempRoot 'runtime'
$ServerLog = Join-Path $TempRoot 'server.log'
$ServerProcess = $null

function Assert-True([bool]$Condition, [string]$Message) { if (-not $Condition) { throw $Message } }
function Get-FreePort { $listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,0);$listener.Start();$port=([Net.IPEndPoint]$listener.LocalEndpoint).Port;$listener.Stop();return $port }
function Write-JsonFile([string]$Path,$Value) { $dir=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $dir -PathType Container)){New-Item -ItemType Directory -Path $dir -Force|Out-Null};[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 50)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false)) }
function Invoke-Api([string]$Url,[string]$Method='GET',$Body=$null,[hashtable]$Headers=@{}) {
  $params=@{UseBasicParsing=$true;Uri=$Url;Method=$Method;TimeoutSec=15;Headers=$Headers}
  if($null-ne$Body){$params.ContentType='application/json; charset=utf-8';$params.Body=$Body|ConvertTo-Json -Depth 50 -Compress}
  try{$r=Invoke-WebRequest @params;return [pscustomobject]@{Status=[int]$r.StatusCode;Json=($r.Content|ConvertFrom-Json);Raw=$r.Content}}
  catch{$resp=$_.Exception.Response;if($null-eq$resp){throw};$reader=New-Object IO.StreamReader($resp.GetResponseStream());try{$raw=$reader.ReadToEnd()}finally{$reader.Dispose()};return [pscustomobject]@{Status=[int]$resp.StatusCode.value__;Json=$(try{$raw|ConvertFrom-Json}catch{$null});Raw=$raw}}
}
function Stop-TestServer { if($ServerProcess-and-not$ServerProcess.HasExited){Stop-Process -Id $ServerProcess.Id -Force -ErrorAction SilentlyContinue} }
function Get-Card($Payload,[string]$Id){return @($Payload.projects|Where-Object{[string]$_.id-eq$Id}|Select-Object -First 1)[0]}
function Get-Revision([string]$Path){$i=Get-Item -LiteralPath $Path;return $i.LastWriteTimeUtc.ToString('o')+'|'+(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}

try {
  New-Item -ItemType Directory -Path (Join-Path $CanonicalRoot 'data'),(Join-Path $CanonicalRoot 'project_files'),(Join-Path $RuntimeRoot 'data'),(Join-Path $RuntimeRoot 'project_files') -Force|Out-Null
  Copy-Item -LiteralPath (Join-Path $RepoRoot 'index.html') -Destination (Join-Path $RuntimeRoot 'index.html') -Force
  $noteExact = "First line`r`n`r`nSecond line " + '<script>alert(''x'')</script>' + " " + [char]0x2014 + " caf" + [char]0x00e9
  $projects=[ordered]@{meta=@{name='Synthetic project history test';source='isolated-fixture'};projects=@(
    [ordered]@{id='history-alpha';title='Synthetic Alpha';status='running';riskColour='amber';owner='Owner A';projectLead='Lead A';reviewDate='2026-08-10';blockerReason='';nextAction='Original action';next='Original action';notes=$noteExact;context='Synthetic context';lastUpdated='2026-08-01T10:00:00+09:30';updatedBy='fixture'},
    [ordered]@{id='history-blank';title='Synthetic Blank';status='backlog';riskColour='green';nextAction='';next='';notes='';context='Synthetic';lastUpdated='';updatedBy=''}
  )}
  Write-JsonFile (Join-Path $CanonicalRoot 'data\projects.json') $projects
  [IO.File]::WriteAllText((Join-Path $CanonicalRoot 'data\card_updates.jsonl'),'',[Text.UTF8Encoding]::new($false))
  New-Item -ItemType Directory -Path (Join-Path $CanonicalRoot 'project_files\history-alpha'),(Join-Path $CanonicalRoot 'project_files\history-blank') -Force|Out-Null
  $port=Get-FreePort;$arguments='-NoProfile -ExecutionPolicy Bypass -File "{0}" -RootPath "{1}" -SourceRoot "{2}" -TeamRoot "{3}" -CanonicalRoot "{3}" -LocalMirrorRoot "{1}" -RuntimeMode team-canonical -Port {4} -LogPath "{5}"'-f (Join-Path $RepoRoot 'serve_kanban.ps1'),$RuntimeRoot,$RepoRoot,$CanonicalRoot,$port,$ServerLog
  $ServerProcess=Start-Process -FilePath (Get-Command powershell.exe).Source -ArgumentList $arguments -WindowStyle Hidden -PassThru
  $base="http://127.0.0.1:$port";for($i=0;$i-lt60;$i++){Start-Sleep -Milliseconds 200;try{if((Invoke-Api "$base/api/health").Status-eq200){break}}catch{};if($ServerProcess.HasExited){throw "Server exited before health check. $ServerLog"}}
  $state=Invoke-Api "$base/api/sync-state";Assert-True($state.Status-eq200) 'Initial sync-state failed.'
  $payload=(Invoke-Api "$base/data/projects.json").Json;$old=(Get-Card $payload 'history-alpha').nextAction
  $firstPayload=$payload|ConvertTo-Json -Depth 50|ConvertFrom-Json;$firstCard=Get-Card $firstPayload 'history-alpha';$firstCard.nextAction='Replacement action';$firstCard.next='Replacement action';$firstCard.PSObject.Properties.Remove('projectHistory');$firstPayload|Add-Member -NotePropertyName auditEvents -NotePropertyValue @([pscustomobject]@{cardId='history-alpha';action='save_update';note='synthetic history save'}) -Force
  $first=Invoke-Api "$base/api/projects" 'POST' $firstPayload @{ 'X-Kanban-Projects-Revision'=$state.Json.projectsRevision };Assert-True($first.Status-eq200) "Next Action save failed: $($first.Raw)"
  $saved=Get-Card $first.Json.canonicalProjects 'history-alpha';$history=@($saved.projectHistory);Assert-True($history.Count-eq1) 'Expected one generated history event.';Assert-True([string]$history[0].type-eq'next_action_changed') 'Expected next_action_changed event.';Assert-True([string]$history[0].previousNextAction-eq$old) 'Previous action was not preserved.';Assert-True([string]$history[0].nextAction-eq'Replacement action') 'New action was not recorded.';Assert-True([string]$saved.notes-eq$noteExact) 'Existing Notes changed during history save.'
  $stateAfter=Invoke-Api "$base/api/sync-state"; $retryPayload=$first.Json.canonicalProjects|ConvertTo-Json -Depth 50|ConvertFrom-Json;$retryPayload|Add-Member -NotePropertyName auditEvents -NotePropertyValue @([pscustomobject]@{cardId='history-alpha';action='save_update'}) -Force;$retry=Invoke-Api "$base/api/projects" 'POST' $retryPayload @{ 'X-Kanban-Projects-Revision'=$stateAfter.Json.projectsRevision };Assert-True($retry.Status-eq200) 'Retry with unchanged canonical value failed.';Assert-True(@((Get-Card $retry.Json.canonicalProjects 'history-alpha').projectHistory).Count-eq1) 'Retry duplicated Project History.'
  $stale=Invoke-Api "$base/api/projects" 'POST' $retryPayload @{ 'X-Kanban-Projects-Revision'=$state.Json.projectsRevision };Assert-True($stale.Status-eq409) 'Stale revision did not return HTTP 409.'
  $notesValue = "Updated notes`r`n`r`nUnicode " + [char]0x2014 + " " + '<b>not HTML</b>';$notesPayload=$retry.Json.canonicalProjects|ConvertTo-Json -Depth 50|ConvertFrom-Json;$notesCard=Get-Card $notesPayload 'history-alpha';$notesCard.notes=$notesValue;$notesPayload|Add-Member -NotePropertyName auditEvents -NotePropertyValue @([pscustomobject]@{cardId='history-alpha';action='save_update';note='notes only'}) -Force;$stateNotes=Invoke-Api "$base/api/sync-state";$notesSave=Invoke-Api "$base/api/projects" 'POST' $notesPayload @{ 'X-Kanban-Projects-Revision'=$stateNotes.Json.projectsRevision };Assert-True($notesSave.Status-eq200) 'Notes-only save failed.';Assert-True([string](Get-Card $notesSave.Json.canonicalProjects 'history-alpha').notes-eq$notesValue) 'Notes were not preserved exactly.';Assert-True(@((Get-Card $notesSave.Json.canonicalProjects 'history-alpha').projectHistory).Count-eq1) 'Notes-only save created a Next Action event.'
  $clearPayload=$notesSave.Json.canonicalProjects|ConvertTo-Json -Depth 50|ConvertFrom-Json;$clearCard=Get-Card $clearPayload 'history-alpha';$clearCard.nextAction='';$clearCard.next='';$clearPayload|Add-Member -NotePropertyName auditEvents -NotePropertyValue @([pscustomobject]@{cardId='history-alpha';action='save_update'}) -Force;$stateClear=Invoke-Api "$base/api/sync-state";$clear=Invoke-Api "$base/api/projects" 'POST' $clearPayload @{ 'X-Kanban-Projects-Revision'=$stateClear.Json.projectsRevision };Assert-True($clear.Status-eq200) 'Clear save failed.'
  $setPayload=$clear.Json.canonicalProjects|ConvertTo-Json -Depth 50|ConvertFrom-Json;$setCard=Get-Card $setPayload 'history-alpha';$setCard.nextAction='Later action';$setCard.next='Later action';$setPayload|Add-Member -NotePropertyName auditEvents -NotePropertyValue @([pscustomobject]@{cardId='history-alpha';action='save_update'}) -Force;$stateSet=Invoke-Api "$base/api/sync-state";$set=Invoke-Api "$base/api/projects" 'POST' $setPayload @{ 'X-Kanban-Projects-Revision'=$stateSet.Json.projectsRevision };Assert-True($set.Status-eq200) 'Set after clear failed.';$historyAfter=@((Get-Card $set.Json.canonicalProjects 'history-alpha').projectHistory);Assert-True($historyAfter.Count-eq3) 'Clear and set should retain three history events.';Assert-True(@($historyAfter|Where-Object { $_.type -eq 'next_action_cleared' }).Count-eq1) 'Missing cleared event.';Assert-True(@($historyAfter|Where-Object { $_.type -eq 'next_action_set' }).Count-eq1) 'Missing set event.'
  $blankPayload=$set.Json.canonicalProjects|ConvertTo-Json -Depth 50|ConvertFrom-Json;$blankCard=Get-Card $blankPayload 'history-blank';$blankCard.nextAction='First blank action';$blankCard.next='First blank action';$blankPayload|Add-Member -NotePropertyName auditEvents -NotePropertyValue @([pscustomobject]@{cardId='history-blank';action='project.created'}) -Force;$stateBlank=Invoke-Api "$base/api/sync-state";$blankSave=Invoke-Api "$base/api/projects" 'POST' $blankPayload @{ 'X-Kanban-Projects-Revision'=$stateBlank.Json.projectsRevision };Assert-True($blankSave.Status-eq200) 'Blank-to-set save failed.';Assert-True(([string](Get-Card $blankSave.Json.canonicalProjects 'history-blank').projectHistory[0].type -eq 'next_action_set')) 'Blank-to-set did not create set event.'
  $html=Get-Content -Raw -LiteralPath (Join-Path $RepoRoot 'index.html');foreach($marker in @('Project Update History','Additional Notes','No automatic project updates have been recorded yet.','function projectContextMarkdown','projectHistoryItems')){Assert-True($html.Contains($marker)) "UI marker missing: $marker"}
  'PROJECT_HISTORY_TESTS_OK'
} finally { Stop-TestServer; if($KeepTemp){"KEPT_TEMP_ROOT=$TempRoot"}elseif(Test-Path -LiteralPath $TempRoot){[IO.Directory]::Delete($TempRoot,$true)} }
